<ul id="social-media-list-wrapper" class="clearfix">
	<li>
    	<div class="twitter-wrapper media-wrapper">
        	<a class="twitter-timeline" href="https://twitter.com/RaMonaLaRue" data-widget-id="397491287453995010">Tweets by @RaMonaLaRue</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            <h2>Follow us <br /> on twitter</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
            <a target="_blank" href="https://twitter.com/RaMonaLaRue" class="sm-button">Visit Now</a>
        </div>
    </li>
	<li>
    	<div class="facebook-wrapper media-wrapper">
        	<iframe src="https://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Framonalaruebyarianne&width=300px&height=395&colorscheme=light&show_faces=false&header=false&stream=true&show_border=true&appId=430996286940981" width="300px" height="395px"></iframe>
            <h2>Friend us <br /> on facebook</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
            <a target="_blank" href="https://www.facebook.com/ramonalaruebyarianne" class="sm-button">Visit Now</a>
        </div>
    </li>
	<li>
    	<div class="instagram-wrapper media-wrapper">
        	<!-- www.intagme.com -->
			<iframe src="http://www.intagme.com/in/?u=cmFtb25hbGFydWV8aW58OTV8M3w0fHxub3w0fHVuZGVmaW5lZA==" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:297px; height: 396px" ></iframe>
            <h2>Visit us <br /> on instagram</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad </p>
            <a target="_blank" href="http://instagram.com/ramonalarue/" class="sm-button">Visit Now</a>
        </div>
    </li>
</ul>