<?php if(Mage::getStoreConfig("slideshow/general/enable")): ?>

	<script src="<?php echo $this->getJsUrl('slideshow/jquery.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->getJsUrl('slideshow/jquery.mobile.customized.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->getJsUrl('slideshow/jquery.easing.1.3.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->getJsUrl('slideshow/camera.min.js'); ?>" type="text/javascript"></script>
    <link href="<?php echo $this->getSkinUrl('slideshow/css/camera.css'); ?>" type="text/css" rel="stylesheet"></link>

	<style type="text/css">
    .fluid_container {
        margin: 0 auto;
        max-width: <?php echo Mage::getStoreConfig("slideshow/general/width"); ?>px;
        width: 100%;
    }
    </style>
    <?php
        $now = Mage::getModel('core/date')->timestamp(time());
        $dateStart = date('Y-m-d' . ' 00:00:00', $now);
        $dateEnd = date('Y-m-d' . ' 23:59:00', $now); 
        
        $slides = Mage::getModel('slideshow/slides')
        ->getCollection()
        ->addFieldToFilter('filename', array('neq' => ''))
        ->addFieldToFilter('status', array('eq' => '1'))
        ->addFieldToFilter('start_date', 
				 array(
					 array('to' => Mage::getModel('core/date')->gmtDate()),
					 array('start_date', 'null'=>'')
					 )
		)
	   	->addFieldToFilter('end_date',
				 array(
					 array('gteq' => Mage::getModel('core/date')->gmtDate()),
					 array('end_date', 'null'=>'')
					 )
		)		
		->setOrder("sort_order","ASC");	
		//var_dump($slides->getSelectSql(true));
		
         ?>
    <?php if(count($slides) > 0): $titles = array(); ?>
	<div class="fluid_container">
    	<div class="camera_wrap <?php echo Mage::getStoreConfig("slideshow/general/skin"); ?>" id="camera_wrap_1">
        <?php foreach ($slides as $item): $titles[] = $item->getTitle();?>
                <div data-thumb="<?php echo str_replace("/slides/","/slides/thumbs/", Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item->getFilename() )?>" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item->getFilename() ?>" data-link="<?php echo $item->getSlideUrl() ?>" data-target="<?php echo $item->getSlideTarget() ?>">
                    <?php if($item->getSlideContent()): ?>
                    <div class="fadeIn camera_effected content-wrapper drop-shadow raised">
                        <?php 
                        $content = $item->getSlideContent();
                        $btntext = $item->getActionButtonText();
                        $url = $item->getSlideUrl();
                        echo !empty($content) ? sprintf('<p>%s</p>', $content) : '';
                        echo !empty($url) ? sprintf("<a href='%s'>%s</a>", $url, $btntext) : '';
                        ?>
                    </div>
                    <?php endif; ?>
                </div>             
        <?php endforeach;?>
        </div>
        <ul>
        <?php foreach($titles as $key => $title): ?>
            <li class='custom-pager' id='thum-pager-<?php echo $key ?>'>
                <?php echo $title; ?>
            </li>   
        <?php endforeach;?>       
        </ul>
    </div>
    
    <script type="text/javascript">
	var total_slides = <?php echo count($slides); ?>
    //jQuery.noConflict();
    jQuery(document).ready(function(){
        jQuery('#camera_wrap_1').camera({
            alignment: 'center',
            autoAdvance: true,
            mobileAutoAdvance: true,
            barDirection: '<?php echo Mage::getStoreConfig("slideshow/general/bar_direction"); ?>',
            barPosition: '<?php echo Mage::getStoreConfig("slideshow/general/bar_position"); ?>',
            cols: <?php echo Mage::getStoreConfig("slideshow/general/cols"); ?>,
            easing: '<?php echo Mage::getStoreConfig("slideshow/effects/easing"); ?>',
            mobileEasing: '<?php echo Mage::getStoreConfig("slideshow/effects/mobile_easing"); ?>',
            overlayer: <?php echo Mage::getStoreConfig("slideshow/general/overlayer"); ?>,
            pagination: <?php echo Mage::getStoreConfig("slideshow/general/pagination"); ?>,
            playPause: <?php echo Mage::getStoreConfig("slideshow/general/play_pause"); ?>,
            pauseOnClick: <?php echo Mage::getStoreConfig("slideshow/general/pause_on_click"); ?>,
            pieDiameter: <?php echo Mage::getStoreConfig("slideshow/general/pie_diameter"); ?>,
            piePosition: '<?php echo Mage::getStoreConfig("slideshow/general/pie_position"); ?>',
            portrait: <?php echo Mage::getStoreConfig("slideshow/general/portrait"); ?>,
            rows: <?php echo Mage::getStoreConfig("slideshow/general/rows"); ?>,
            slicedRows: <?php echo Mage::getStoreConfig("slideshow/general/sliced_rows"); ?>,
            slicedCols: <?php echo Mage::getStoreConfig("slideshow/general/sliced_cols"); ?>,
            fx: '<?php echo Mage::getStoreConfig("slideshow/effects/fx"); ?>',
            mobileFx: '<?php echo Mage::getStoreConfig("slideshow/effects/mobile_fx"); ?>',
            gridDifference: <?php echo Mage::getStoreConfig("slideshow/general/grid_difference"); ?>,
            height: '<?php echo Mage::getStoreConfig("slideshow/general/height"); ?>',
            hover: <?php echo Mage::getStoreConfig("slideshow/general/hover"); ?>,
            slideOn: '<?php echo Mage::getStoreConfig("slideshow/general/slide_on"); ?>',
            thumbnails: <?php echo Mage::getStoreConfig("slideshow/general/thumbnails"); ?>,
            time: <?php echo Mage::getStoreConfig("slideshow/general/time"); ?>,
            transPeriod: <?php echo Mage::getStoreConfig("slideshow/general/trans_period"); ?>,
            loader: '<?php echo Mage::getStoreConfig("slideshow/effects/loader"); ?>',
            loaderColor: '#<?php echo Mage::getStoreConfig("slideshow/effects/loader_color"); ?>',
            loaderBgColor: '#<?php echo Mage::getStoreConfig("slideshow/effects/loader_bg_color"); ?>',
            loaderOpacity: <?php echo Mage::getStoreConfig("slideshow/effects/loader_opacity"); ?>,
            loaderPadding: <?php echo Mage::getStoreConfig("slideshow/effects/loader_padding"); ?>,
            loaderStroke: <?php echo Mage::getStoreConfig("slideshow/effects/loader_stroke"); ?>,
            minHeight: '',
            navigation: <?php echo Mage::getStoreConfig("slideshow/effects/navigation"); ?>,
            navigationHover: <?php echo Mage::getStoreConfig("slideshow/effects/navigation_on_hover"); ?>,
            mobileNavHover: <?php echo Mage::getStoreConfig("slideshow/effects/mobile_nav_hover"); ?>,
            opacityOnGrid: <?php echo Mage::getStoreConfig("slideshow/effects/opacity_on_grid"); ?>,
    		onLoaded: function(){
  				var ind = jQuery('.camera_wrap').find('.camera_target .cameraSlide.cameracurrent').index()
				jQuery('.custom-pager').css('color', 'black');
				var index = total_slides == (ind + 1) ? 0 : (ind + 1);
				jQuery('#thum-pager-' + index).css('color', 'red');
				
			}
        });
		jQuery('.custom-pager').click(function(){
			alert('click');
			jQuery('#camera_wrap_1').cameraPause(); //.nextSlide(2);
        });
    });
    
    </script>
    <?php endif; ?>
<?php endif; ?>